/**
 * Document Formats, Layout Presets, Color Themes & Boilerplates
 * For STAS-RG Research Generator
 */

export const DOCUMENT_FORMATS = {
    a4_flyer: {
        id: 'a4_flyer',
        name: 'A4 Flyer Standar',
        tagline: '210 × 297 mm',
        description: 'Format standar publikasi cetak A4 portrait dengan proporsi seimbang untuk leaflet dan poster riset.',
        aspectRatio: '1:1.414',
        canvasWidth: 794,
        canvasHeight: 1123,
        padding: '68px 57px 57px 57px',
        supportsPresets: true,
        bestFor: 'Publikasi leaflet cetak, arsip berkas, dan poster 1 halaman',
    },
    roll_banner: {
        id: 'roll_banner',
        name: 'X-Banner',
        tagline: '60 × 160 cm',
        description: 'Format vertikal tinggi dengan hierarki visual banner pameran, judul besar, dan QR sejajar eye-level.',
        aspectRatio: '1:2.67',
        canvasWidth: 600,
        canvasHeight: 1600,
        padding: '70px 48px 55px 48px',
        supportsPresets: false,
        bestFor: 'Booth pameran, expo teknologi, seminar, dan open house lab',
    },
    factsheet_2col: {
        id: 'factsheet_2col',
        name: 'Factsheet 2',
        tagline: 'Executive Brief',
        description: 'Format ringkas 2-kolom terstruktur: kolom kiri untuk problem/spesifikasi teknis, kolom kanan untuk foto & manfaat.',
        aspectRatio: '1:1.414',
        canvasWidth: 794,
        canvasHeight: 1123,
        padding: '60px 50px 50px 50px',
        supportsPresets: false,
        bestFor: 'Ringkasan eksekutif investor, pitch brief mitra, dan katalog produk',
    },
    pitch_poster: {
        id: 'pitch_poster',
        name: 'Pitch Deck Poster',
        tagline: '16:9 Widescreen',
        description: 'Format lanskap horizontal 16:9 ideal untuk display monitor TV, presentasi investor, dan digital signage.',
        aspectRatio: '16:9',
        canvasWidth: 1200,
        canvasHeight: 675,
        padding: '48px 56px 45px 56px',
        supportsPresets: false,
        bestFor: 'Layar TV booth pameran, slide pitch, simposium, dan digital kiosk',
    },
    social_feed: {
        id: 'social_feed',
        name: 'Instagram / LinkedIn Feed',
        tagline: '1080 × 1080 px',
        description: 'Format persegi 1:1 visual kontemporer siap publikasi di feed media sosial, carousel riset, dan LinkedIn.',
        aspectRatio: '1:1',
        canvasWidth: 1080,
        canvasHeight: 1080,
        padding: '44px 44px 36px 44px',
        supportsPresets: false,
        bestFor: 'Feed Instagram CoE STAS-RG, LinkedIn update, dan broadcast WhatsApp',
    },
    social_story: {
        id: 'social_story',
        name: 'Instagram Story / WA Status',
        tagline: '1080 × 1920 px',
        description: 'Format vertikal seluler 9:16 dengan layout ramping untuk Instagram Story, WhatsApp Status, dan TikTok/Reels.',
        aspectRatio: '9:16',
        canvasWidth: 1080,
        canvasHeight: 1920,
        padding: '60px 48px 52px 48px',
        supportsPresets: false,
        bestFor: 'Story Instagram, Status WhatsApp pengelola lab, dan flyer seluler',
    },
    brochure_trifold: {
        id: 'brochure_trifold',
        name: 'Brosur A4 Lipat 3',
        tagline: '29.7 × 21 cm',
        description: 'Format brosur cetak A4 landscape lipat 3 (trifold). Terbagi dalam 3 kotak panel berukuran 9.9 × 21 cm: Kotak 1 (Kiri), Kotak 2 (Tengah), dan Kotak 3 (Kanan / Cover).',
        aspectRatio: '1.414:1',
        canvasWidth: 1123,
        canvasHeight: 794,
        padding: '24px 20px 20px 20px',
        supportsPresets: false,
        bestFor: 'Brosur pameran lipat 3, leaflet profil riset 3 kolom, dan katalog inovasi',
    },
};

export const COLOR_THEMES = {
    stas_official: {
        id: 'stas_official',
        name: 'CoE STAS-RG Official',
        tagline: 'Forest Green Resmi',
        primary: '#0AB600',
        primaryDark: '#083820',
        primaryLight: '#15803d',
        accent: '#10b981',
        badgeBg: '#0AB600',
        badgeText: '#ffffff',
        headerText: '#0AB600',
        border: '#0AB600',
        bgAccent: '#ecfdf5',
        cardBorder: '#d1fae5',
        darkCanvasBg: '#07150e',
        darkCardBg: '#0e241b',
        previewRing: 'ring-[#0AB600]',
        swatchClass: 'from-[#0AB600] to-[#15803d]',
    },
    ocean_tech: {
        id: 'ocean_tech',
        name: 'Ocean Tech & Marine',
        tagline: 'Deep Navy & Cyan',
        primary: '#0F2B48',
        primaryDark: '#091b2e',
        primaryLight: '#0284c7',
        accent: '#06b6d4',
        badgeBg: '#0F2B48',
        badgeText: '#ffffff',
        headerText: '#0F2B48',
        border: '#0284c7',
        bgAccent: '#f0f9ff',
        cardBorder: '#bae6fd',
        darkCanvasBg: '#071320',
        darkCardBg: '#0d2238',
        previewRing: 'ring-[#0F2B48]',
        swatchClass: 'from-[#0F2B48] to-[#0284c7]',
    },
    crimson_innovation: {
        id: 'crimson_innovation',
        name: 'Crimson Innovation',
        tagline: 'Tel-U Crimson & Amber',
        primary: '#8B1538',
        primaryDark: '#5c0d24',
        primaryLight: '#be123c',
        accent: '#f59e0b',
        badgeBg: '#8B1538',
        badgeText: '#ffffff',
        headerText: '#8B1538',
        border: '#8B1538',
        bgAccent: '#fff1f2',
        cardBorder: '#fecdd3',
        darkCanvasBg: '#17060b',
        darkCardBg: '#2a0c16',
        previewRing: 'ring-[#8B1538]',
        swatchClass: 'from-[#8B1538] to-[#be123c]',
    },
    slate_monochrome: {
        id: 'slate_monochrome',
        name: 'Executive Slate',
        tagline: 'Platinum & Charcoal',
        primary: '#1E293B',
        primaryDark: '#0f172a',
        primaryLight: '#475569',
        accent: '#64748b',
        badgeBg: '#1E293B',
        badgeText: '#ffffff',
        headerText: '#1E293B',
        border: '#334155',
        bgAccent: '#f8fafc',
        cardBorder: '#e2e8f0',
        darkCanvasBg: '#0b0f19',
        darkCardBg: '#151e2e',
        previewRing: 'ring-[#1E293B]',
        swatchClass: 'from-[#1E293B] to-[#475569]',
    },
    cyber_teal: {
        id: 'cyber_teal',
        name: 'Cyber Teal & Neon',
        tagline: 'Emerald & Cyan Matrix',
        primary: '#059669',
        primaryDark: '#022c22',
        primaryLight: '#10b981',
        accent: '#06b6d4',
        badgeBg: '#059669',
        badgeText: '#ffffff',
        headerText: '#059669',
        border: '#059669',
        bgAccent: '#ecfdf5',
        cardBorder: '#a7f3d0',
        darkCanvasBg: '#041d17',
        darkCardBg: '#08332b',
        previewRing: 'ring-[#059669]',
        swatchClass: 'from-[#059669] to-[#06b6d4]',
    },
    solar_amber: {
        id: 'solar_amber',
        name: 'Solar Amber & Orange',
        tagline: 'Warm Energy & Agro',
        primary: '#D97706',
        primaryDark: '#451a03',
        primaryLight: '#f59e0b',
        accent: '#ea580c',
        badgeBg: '#D97706',
        badgeText: '#ffffff',
        headerText: '#D97706',
        border: '#D97706',
        bgAccent: '#fffbeb',
        cardBorder: '#fde68a',
        darkCanvasBg: '#1f1304',
        darkCardBg: '#331e07',
        previewRing: 'ring-[#D97706]',
        swatchClass: 'from-[#D97706] to-[#ea580c]',
    },
    royal_purple: {
        id: 'royal_purple',
        name: 'Royal Purple AI',
        tagline: 'Deep Violet & Indigo',
        primary: '#6D28D9',
        primaryDark: '#2e1065',
        primaryLight: '#8b5cf6',
        accent: '#a855f7',
        badgeBg: '#6D28D9',
        badgeText: '#ffffff',
        headerText: '#6D28D9',
        border: '#6D28D9',
        bgAccent: '#f5f3ff',
        cardBorder: '#ddd6fe',
        darkCanvasBg: '#130924',
        darkCardBg: '#21133b',
        previewRing: 'ring-[#6D28D9]',
        swatchClass: 'from-[#6D28D9] to-[#8b5cf6]',
    },
    electric_azure: {
        id: 'electric_azure',
        name: 'Electric Blue & Aero',
        tagline: 'Sapphire & Sky Blue',
        primary: '#2563EB',
        primaryDark: '#172554',
        primaryLight: '#3b82f6',
        accent: '#38bdf8',
        badgeBg: '#2563EB',
        badgeText: '#ffffff',
        headerText: '#2563EB',
        border: '#2563EB',
        bgAccent: '#eff6ff',
        cardBorder: '#bfdbfe',
        darkCanvasBg: '#0a152e',
        darkCardBg: '#122347',
        previewRing: 'ring-[#2563EB]',
        swatchClass: 'from-[#2563EB] to-[#38bdf8]',
    },
    custom: {
        id: 'custom',
        name: 'Custom Brand Palette',
        tagline: 'Pilih Warna Hex Sendiri',
        primary: '#0AB600',
        primaryDark: '#083820',
        primaryLight: '#15803d',
        accent: '#10b981',
        badgeBg: '#0AB600',
        badgeText: '#ffffff',
        headerText: '#0AB600',
        border: '#0AB600',
        bgAccent: '#ecfdf5',
        cardBorder: '#d1fae5',
        darkCanvasBg: '#07150e',
        darkCardBg: '#0e241b',
        previewRing: 'ring-indigo-500',
        swatchClass: 'from-indigo-500 via-purple-500 to-pink-500',
    },
};

export const FLYER_FONTS = {
    plus_jakarta: {
        id: 'plus_jakarta',
        name: 'Plus Jakarta Sans',
        tagline: 'Modern & Bersih',
        fontFamily: "'Plus Jakarta Sans', sans-serif",
        category: 'Sans-Serif',
        description: 'Tipografi terstandarisasi Telkom University & CoE STAS-RG yang jernih dan sangat mudah dibaca.',
    },
    outfit: {
        id: 'outfit',
        name: 'Outfit',
        tagline: 'Kontemporer Futuristik',
        fontFamily: "'Outfit', sans-serif",
        category: 'Display Sans',
        description: 'Bentuk geometris bulat modern cocok untuk display produk AI, IoT, dan teknologi masa depan.',
    },
    space_grotesk: {
        id: 'space_grotesk',
        name: 'Space Grotesk',
        tagline: 'Tech & Engineering',
        fontFamily: "'Space Grotesk', sans-serif",
        category: 'Tech Grotesk',
        description: 'Sentuhan teknikal bernuansa lab kedirgantaraan, robotika, dan riset sains terapan.',
    },
    inter: {
        id: 'inter',
        name: 'Inter',
        tagline: 'Korporat & Netral',
        fontFamily: "'Inter', sans-serif",
        category: 'Universal Sans',
        description: 'Tingkat keterbacaan micro-text tertinggi untuk poin spesifikasi padat.',
    },
    montserrat: {
        id: 'montserrat',
        name: 'Montserrat',
        tagline: 'Bold & Impact',
        fontFamily: "'Montserrat', sans-serif",
        category: 'Geometric Sans',
        description: 'Karakter judul yang tegas dan menarik perhatian di display pameran dan poster.',
    },
    playfair: {
        id: 'playfair',
        name: 'Playfair Display',
        tagline: 'Akademis & Formal',
        fontFamily: "'Playfair Display', Georgia, serif",
        category: 'Modern Serif',
        description: 'Gaya elegan berwibawa untuk prosiding ilmiah simposium dan piagam riset resmi.',
    },
};

export const FLYER_PATTERNS = {
    none: {
        id: 'none',
        name: 'Clean Flat',
        tagline: 'Solid Minimalis',
        description: 'Latar polos bersih tanpa motif untuk kemudahan cetak dan tampilan minimalis.',
        cssPattern: 'none',
    },
    dots: {
        id: 'dots',
        name: 'Dot Matrix',
        tagline: 'Titik Halus Modern',
        description: 'Pola titik matriks berjarak halus bernuansa komputasi dan sirkuit modern.',
        cssPattern: 'radial-gradient(currentColor 1px, transparent 1px)',
        bgSize: '16px 16px',
        opacity: 0.05,
    },
    grid: {
        id: 'grid',
        name: 'Blueprint Grid',
        tagline: 'Garis Kotak Teknik',
        description: 'Kisi-kisi grid teknik presisi seperti lembar kalkulasi arsitektur riset.',
        cssPattern: 'linear-gradient(to right, currentColor 1px, transparent 1px), linear-gradient(to bottom, currentColor 1px, transparent 1px)',
        bgSize: '24px 24px',
        opacity: 0.04,
    },
    mesh: {
        id: 'mesh',
        name: 'Radial Mesh',
        tagline: 'Gradasi Aura Lembut',
        description: 'Highlight pendaran cahaya lembut di sudut atas kanvas flyer.',
        cssPattern: 'radial-gradient(circle at 100% 0%, var(--accent-glow, rgba(10,182,0,0.08)) 0%, transparent 50%)',
        opacity: 1,
    },
};

export const PRINT_MODES = {
    light: {
        id: 'light',
        name: 'Light Print Mode',
        tagline: 'Hemat Tinta & Cetak Fisik',
        description: 'Latar putih bersih dengan kontras tinggi, dioptimalkan untuk cetak kertas/spanduk fisik dan menghemat tinta printer.',
        bg: '#ffffff',
        textColor: '#1a1a1a',
        mutedText: '#4b5563',
        cardBg: '#f9fafb',
        borderColor: '#e5e7eb',
    },
    dark: {
        id: 'dark',
        name: 'Dark Modern Mode',
        tagline: 'Digital Kiosk & High Contrast',
        description: 'Tampilan tema gelap modern berkesan futuristik untuk display monitor TV, presentasi booth pameran, dan tablet interaktif.',
        bg: '#0B0F17',
        textColor: '#f3f4f6',
        mutedText: '#9ca3af',
        cardBg: '#121824',
        borderColor: '#1f293d',
    },
};

export const BOILERPLATES = {
    stas_default: {
        id: 'stas_default',
        name: 'CoE STAS-RG Standar',
        subtitle: 'CENTER OF EXCELLENCE STAS-RG',
        footer_website: 'www.stas-rg.com',
        footer_instagram: '@stas.rg',
        footer_youtube: '@stas_rg',
        descriptionBadge: 'Standar Lab Riset Telkom University',
    },
    industry_kedaireka: {
        id: 'industry_kedaireka',
        name: 'Kolaborasi Industri & Kedaireka',
        subtitle: 'KEDAIREKA MATCHING FUND & INDUSTRIAL PARTNERSHIP',
        footer_website: 'kedaireka.id / www.stas-rg.com',
        footer_instagram: '@stas.rg',
        footer_youtube: '@stas_rg',
        descriptionBadge: 'Program Kolaborasi Industri & Hilirisasi',
    },
    academic_conference: {
        id: 'academic_conference',
        name: 'Konferensi & Expo Ilmiah',
        subtitle: 'RESEARCH & INNOVATION EXPO / PROCEEDINGS',
        footer_website: 'www.stas-rg.com/publications',
        footer_instagram: '@stas.rg',
        footer_youtube: '@stas_rg',
        descriptionBadge: 'Publikasi Simposium & Jurnal Ilmiah',
    },
    lab_capstone: {
        id: 'lab_capstone',
        name: 'Capstone & Lab Showcase',
        subtitle: 'ADVANCED EMBEDDED & INTELLIGENT SYSTEMS LAB',
        footer_website: 'www.stas-rg.com/lab',
        footer_instagram: '@stas.rg',
        footer_youtube: '@stas_rg',
        descriptionBadge: 'Showcase Prototipe & Tugas Akhir Unggulan',
    },
};

export const LAYOUT_PRESETS = {
    balanced: {
        id: 'balanced',
        mode: 'Mode A',
        name: 'Standar (Balanced)',
        tagline: 'Proporsi Seimbang',
        description: 'Proporsi seimbang antara foto produk dan poin spesifikasi.',
        bestFor: 'Proyek kombinasi hardware & software terintegrasi',
        badgeColor: 'bg-[#0AB600]/10 text-[#0AB600] dark:bg-[#0AB600]/10 dark:text-[#0AB600] border-[#0AB600]/30',
        activeRing: 'ring-[#0AB600] border-[#0AB600] bg-[#0AB600]/10',
        styles: {
            imageHeight: 205,
            imageContainerPadding: '0px',
            titleFontSize: '21pt',
            descFontSize: '9.5pt',
            descMarginBottom: '14px',
            sectionMarginBottom: '9px',
            sectionTitleFontSize: '10.5pt',
            sectionContentFontSize: '9pt',
            sectionLineHeight: 1.4,
            headerMarginBottom: '10px',
            iconSize: '24px',
            iconInnerSize: '13px',
        },
        limits: {
            title: { max: 65, warn: 50, label: 'Judul Flyer', desc: 'Maks 2 baris (21pt)' },
            subtitle: { max: 45, warn: 35, label: 'Subtitle Banner', desc: 'Maks 1 baris badge' },
            description: { max: 420, warn: 330, label: 'Deskripsi Singkat', desc: 'Ringkasan sistem & inovasi' },
            benefits: { max: 270, warn: 210, label: 'Poin Manfaat', desc: 'Dampak & efisiensi penerapan' },
            specifications: { max: 270, warn: 210, label: 'Poin Spesifikasi', desc: 'Sensor & komponen teknis' },
            problem: { max: 220, warn: 175, label: 'Problem', desc: 'Uraian kendala di lapangan' },
            solution: { max: 220, warn: 175, label: 'Solution', desc: 'Solusi teknologi terapan' },
        },
    },

    visual_heavy: {
        id: 'visual_heavy',
        mode: 'Mode B',
        name: 'Visual-Heavy',
        tagline: 'Foto Prototipe Dominan',
        description: 'Foto prototipe/alat riset berukuran lebih besar (cocok untuk proyek hardware, IoT, atau alat fisik).',
        bestFor: 'Hardware, IoT, Robotika, Mekanik & Prototipe Fisik',
        badgeColor: 'bg-blue-50 text-blue-800 dark:bg-blue-950 dark:text-blue-300 border-blue-200 dark:border-blue-800',
        activeRing: 'ring-blue-600 border-blue-600 bg-blue-50/40 dark:bg-blue-950/20',
        styles: {
            imageHeight: 270,
            imageContainerPadding: '0px',
            titleFontSize: '19.5pt',
            descFontSize: '9pt',
            descMarginBottom: '9px',
            sectionMarginBottom: '6px',
            sectionTitleFontSize: '10pt',
            sectionContentFontSize: '8.5pt',
            sectionLineHeight: 1.35,
            headerMarginBottom: '8px',
            iconSize: '22px',
            iconInnerSize: '12px',
        },
        limits: {
            title: { max: 65, warn: 50, label: 'Judul Flyer', desc: 'Maks 2 baris (19.5pt)' },
            subtitle: { max: 45, warn: 35, label: 'Subtitle Banner', desc: 'Maks 1 baris badge' },
            description: { max: 280, warn: 220, label: 'Deskripsi Singkat', desc: 'Ringkas & to the point' },
            benefits: { max: 200, warn: 155, label: 'Poin Manfaat', desc: 'Poin manfaat ringkas' },
            specifications: { max: 200, warn: 155, label: 'Poin Spesifikasi', desc: 'Spesifikasi hardware utama' },
            problem: { max: 160, warn: 125, label: 'Problem', desc: 'Masalah utama ringkas' },
            solution: { max: 160, warn: 125, label: 'Solution', desc: 'Solusi teknologi ringkas' },
        },
    },

    text_heavy: {
        id: 'text_heavy',
        mode: 'Mode C',
        name: 'Text/Spec-Heavy',
        tagline: 'Ruang Spesifikasi Luas',
        description: 'Ruang poin teknis lebih luas (cocok untuk proyek software, algoritma, atau AI).',
        bestFor: 'Software, AI, Machine Learning, Cybersecurity & Algoritma',
        badgeColor: 'bg-purple-50 text-purple-800 dark:bg-purple-950 dark:text-purple-300 border-purple-200 dark:border-purple-800',
        activeRing: 'ring-purple-600 border-purple-600 bg-purple-50/40 dark:bg-purple-950/20',
        styles: {
            imageHeight: 135,
            imageContainerPadding: '0px',
            titleFontSize: '21pt',
            descFontSize: '9.5pt',
            descMarginBottom: '14px',
            sectionMarginBottom: '12px',
            sectionTitleFontSize: '10.5pt',
            sectionContentFontSize: '9.2pt',
            sectionLineHeight: 1.45,
            headerMarginBottom: '10px',
            iconSize: '25px',
            iconInnerSize: '13px',
        },
        limits: {
            title: { max: 65, warn: 50, label: 'Judul Flyer', desc: 'Maks 2 baris (21pt)' },
            subtitle: { max: 45, warn: 35, label: 'Subtitle Banner', desc: 'Maks 1 baris badge' },
            description: { max: 540, warn: 420, label: 'Deskripsi Singkat', desc: 'Uraian arsitektur & cara kerja' },
            benefits: { max: 360, warn: 280, label: 'Poin Manfaat', desc: 'Uraian keunggulan & metrik' },
            specifications: { max: 360, warn: 280, label: 'Poin Spesifikasi', desc: 'Spesifikasi model, API, arsitektur' },
            problem: { max: 280, warn: 220, label: 'Problem', desc: 'Latar belakang kendala' },
            solution: { max: 280, warn: 220, label: 'Solution', desc: 'Detail arsitektur solusi' },
        },
    },
};

export const DESIGN_STYLES = {
    classic_standard: {
        id: 'classic_standard',
        name: 'CoE Classic Standard',
        tagline: 'Struktur Resmi & Terbukti',
        description: 'Hierarki tata letak resmi CoE STAS-RG klasik dengan proporsi seimbang, badge solid, dan garis pembatas bersih.',
        badgeColor: 'bg-emerald-50 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-300 border-emerald-200',
        bestFor: 'Publikasi resmi lab, berkas arsip riset, dan laporan standar',
    },
    modern_split: {
        id: 'modern_split',
        name: 'Modern Split Hero',
        tagline: 'Asimetris & Visual Dinamis',
        description: 'Tata letak modern dengan header beraksen kuat, hero frame asimetris, dan kartu solusi dengan highlight gradien halus.',
        badgeColor: 'bg-blue-50 text-blue-800 dark:bg-blue-950 dark:text-blue-300 border-blue-200',
        bestFor: 'Showcase prototipe hardware unggulan, expo teknologi, dan leaflet produk',
    },
    infographic_cards: {
        id: 'infographic_cards',
        name: 'Infographic Cards',
        tagline: 'Modul Kartu Berbingkai & Eye-Catching',
        description: 'Desain infografis berbasis kotak kartu rounded dengan highlight problem-solution berbentuk alur inovasi dan badge pill tegas.',
        badgeColor: 'bg-amber-50 text-amber-800 dark:bg-amber-950 dark:text-amber-300 border-amber-200',
        bestFor: 'Kolaborasi industri Kedaireka, pitch investor, dan pameran interaktif',
    },
    minimal_grid: {
        id: 'minimal_grid',
        name: 'Minimalist Swiss Grid',
        tagline: 'Tipografi Tajam & Arsitektur Bersih',
        description: 'Desain presisi tinggi dengan batas garis tipis elegan, ruang bernapas lapang, dan tipografi monokromatik kontras tinggi.',
        badgeColor: 'bg-zinc-100 text-zinc-800 dark:bg-zinc-800 dark:text-zinc-200 border-zinc-300',
        bestFor: 'Riset software, algoritma AI, deep tech, dan dokumentasi arsitektur sistem',
    },
    tech_blueprint: {
        id: 'tech_blueprint',
        name: 'Tech Blueprint Matrix',
        tagline: 'Aksen Teknikal & Corner Markers',
        description: 'Desain teknis mutakhir dengan corner bracket markers, garis grid terstruktur, dan aksen badge futuristik.',
        badgeColor: 'bg-cyan-50 text-cyan-800 dark:bg-cyan-950 dark:text-cyan-300 border-cyan-200',
        bestFor: 'Robotika, IoT, Kedirgantaraan, Telekomunikasi & Rekayasa Perangkat Keras',
    },
    glass_minimalist: {
        id: 'glass_minimalist',
        name: 'Glass Minimalist',
        tagline: 'Translucent & Glowing Borders',
        description: 'Gaya modern translucent glassmorphism dengan outline kartu halus, efek kilau lembut, dan kontras tajam.',
        badgeColor: 'bg-indigo-50 text-indigo-800 dark:bg-indigo-950 dark:text-indigo-300 border-indigo-200',
        bestFor: 'Artificial Intelligence, SaaS, Cloud & Solusi Digital Kontemporer',
    },
    academic_brief: {
        id: 'academic_brief',
        name: 'Academic Paper Brief',
        tagline: 'Format Simposium & Prosiding Ilmiah',
        description: 'Format formal 2-kolom seimbang terinspirasi format prosiding IEEE dan jurnal ilmiah internasional.',
        badgeColor: 'bg-purple-50 text-purple-800 dark:bg-purple-950 dark:text-purple-300 border-purple-200',
        bestFor: 'Publikasi konferensi ilmiah, simposium riset, dan laporan akademis',
    },
};

export function getDocumentFormat(formatId) {
    return DOCUMENT_FORMATS[formatId] || DOCUMENT_FORMATS.a4_flyer;
}

export function getColorTheme(themeId, customColors = null) {
    if (themeId === 'custom' && customColors && (customColors.primary || customColors.accent)) {
        const primary = customColors.primary || '#0AB600';
        const accent = customColors.accent || '#10b981';
        return {
            id: 'custom',
            name: 'Custom Brand Palette',
            tagline: 'Kustomisasi Brand Sendiri',
            primary,
            primaryDark: primary,
            primaryLight: accent,
            accent,
            badgeBg: primary,
            badgeText: '#ffffff',
            headerText: primary,
            border: primary,
            bgAccent: `${primary}12`,
            cardBorder: `${primary}33`,
            darkCanvasBg: '#070c14',
            darkCardBg: '#0e1624',
            previewRing: 'ring-indigo-500',
            swatchClass: 'from-indigo-500 via-purple-500 to-pink-500',
        };
    }
    return COLOR_THEMES[themeId] || COLOR_THEMES.stas_official;
}

export function getFlyerFont(fontId) {
    return FLYER_FONTS[fontId] || FLYER_FONTS.plus_jakarta;
}

export function getFlyerPattern(patternId) {
    return FLYER_PATTERNS[patternId] || FLYER_PATTERNS.none;
}

export function getPrintMode(modeId) {
    return PRINT_MODES[modeId] || PRINT_MODES.light;
}

export function getLayoutPreset(presetId) {
    return LAYOUT_PRESETS[presetId] || LAYOUT_PRESETS.balanced;
}

export function getDesignStyle(styleId) {
    return DESIGN_STYLES[styleId] || DESIGN_STYLES.classic_standard;
}

export const AVAILABLE_BLOCK_TYPES = [
    {
        type: 'header',
        name: 'Header & Judul',
        description: 'Judul riset, subtitle, badge kategori, dan logo mitra',
        icon: 'LayoutTemplate',
        defaultColSpan: 12,
        allowedColSpans: [12],
        hasVariants: false,
    },
    {
        type: 'media',
        name: 'Foto Utama / Prototipe',
        description: 'Visual gambar alat riset, poster, atau diagram sistem',
        icon: 'Image',
        defaultColSpan: 12,
        allowedColSpans: [6, 12],
        hasVariants: true,
        variants: [
            { id: 'compact', name: 'Ringkas (160px)' },
            { id: 'standard', name: 'Standar (220px)' },
            { id: 'large', name: 'Besar (290px)' },
        ],
    },
    {
        type: 'description',
        name: 'Deskripsi Singkat',
        description: 'Paragraf ringkasan inovasi dan keunggulan teknologi',
        icon: 'AlignLeft',
        defaultColSpan: 12,
        allowedColSpans: [6, 12],
        hasVariants: true,
        variants: [
            { id: 'clean', name: 'Teks Bersih' },
            { id: 'card', name: 'Kotak Card' },
        ],
    },
    {
        type: 'benefits',
        name: 'Manfaat & Dampak',
        description: 'Daftar poin manfaat dan efisiensi penerapan teknologi',
        icon: 'Sparkles',
        defaultColSpan: 6,
        allowedColSpans: [4, 6, 12],
        hasVariants: true,
        variants: [
            { id: 'cards', name: 'Kartu Berbingkai' },
            { id: 'list', name: 'Daftar Bullet Bersih' },
        ],
    },
    {
        type: 'specifications',
        name: 'Spesifikasi Teknis',
        description: 'Sensor, mikrokontroler, algoritma, dan parameter sistem',
        icon: 'Cpu',
        defaultColSpan: 6,
        allowedColSpans: [4, 6, 12],
        hasVariants: true,
        variants: [
            { id: 'box', name: 'Kotak Spesifikasi' },
            { id: 'chips', name: 'Tag / Chips Modern' },
        ],
    },
    {
        type: 'problem_solution',
        name: 'Problem & Solution',
        description: 'Tantangan industri / lapangan dan solusi terapan yang ditawarkan',
        icon: 'CheckCircle2',
        defaultColSpan: 12,
        allowedColSpans: [6, 12],
        hasVariants: true,
        variants: [
            { id: 'merged_card', name: '1 Card Terpadu' },
            { id: 'split_cards', name: '2 Kolom Terpisah' },
        ],
    },
    {
        type: 'footer_qr',
        name: 'Footer, Kontak & QR Code',
        description: 'QR scan info detail, media sosial (@stas.rg, youtube), dan link website',
        icon: 'QrCode',
        defaultColSpan: 12,
        allowedColSpans: [12],
        hasVariants: true,
        variants: [
            { id: 'full', name: 'Lengkap (QR + Sosmed)' },
            { id: 'compact', name: 'Ringkas (QR Saja)' },
        ],
    },
];

export function getDefaultLayoutSchema(docFormat = 'a4_flyer', designStyle = 'classic_standard') {
    const format = getDocumentFormat(docFormat);
    return {
        canvas: {
            format: docFormat,
            width: format.canvasWidth || 794,
            height: format.canvasHeight || 1123,
            padding: format.padding || '48px 40px',
            orientation: format.aspectRatio === '16:9' || format.aspectRatio === '1.414:1' ? 'landscape' : 'portrait',
        },
        blocks: [
            { id: 'block_header', type: 'header', visible: true, colSpan: 12 },
            { id: 'block_media', type: 'media', visible: true, colSpan: 12, variant: 'standard' },
            { id: 'block_description', type: 'description', visible: true, colSpan: 12, variant: 'clean' },
            { id: 'block_benefits', type: 'benefits', visible: true, colSpan: 6, variant: 'cards' },
            { id: 'block_specifications', type: 'specifications', visible: true, colSpan: 6, variant: 'box' },
            { id: 'block_problem_solution', type: 'problem_solution', visible: true, colSpan: 12, variant: 'merged_card' },
            { id: 'block_footer_qr', type: 'footer_qr', visible: true, colSpan: 12, variant: 'full' },
        ],
    };
}

